version: "3"

services:
  # mininet:
  #   image: mn-stratum-with-scapy
  #   hostname: mininet
  #   container_name: mininet
  #   privileged: true
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./tmp:/tmp
  #     - ./mininet:/mininet
  #   ports:
  #     - "50001:50001"
  #     - "50002:50002"
  #     - "50003:50003"
  #     - "50004:50004"
  #   entrypoint: "/mininet/topo.py"
  onos:
    image: onos3.0
    hostname: onos
    container_name: onos
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
    volumes:
      - ./tmp/onos:/root/onos/apache-karaf-4.2.8/data/tmp
      - /home/onos/Desktop/:/home/onos/Desktop
    environment:
      - ONOS_APPS=gui2,drivers.bmv2
